name: Build
on: [ push, pull_request ]

jobs:
  build:
    uses: okocraft/workflows/.github/workflows/maven.yml@v1
    with:
      java-version: '21'
      package-name: Box-Build-${{ github.run_number }}
      artifact-directory: "./target"
      upload-test-results: false
